import gtm106.weierstrass_equation.linear_change_of_variable.basic
import gtm106.weierstrass_equation.linear_change_of_variable.change_curve
import gtm106.weierstrass_equation.linear_change_of_variable.change_point
import gtm106.weierstrass_equation.linear_change_of_variable.isom_class
import gtm106.weierstrass_equation.linear_change_of_variable.decomposition
